### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by lucasmsoares96** [ThiagoKienbaum/whatsapp-audio-speed-controller-extension#1]
O icone para controlar a velocidade sumiu.

**Comment by ThiagoKienbaum** [comment]
> O icone para controlar a velocidade sumiu.

Opa, vou dar uma olhadinha amanhã e resolvo

**Comment by lucasmsoares96** [comment]
@ThiagoKienbaum  Alguma novidade?
